### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#301] opened 2018-03-28 10:28 UTC
**URL**: http://testing-engine.camelcasetech.com/admin/backend/emails/1/edit
**Path**: Admin> Backend> Emails > Edit
**Description**: Template editor must be CKEditor
![image](https://user-images.githubusercontent.com/11155105/38023781-d638374e-328b-11e8-932f-7d2065da49ec.png)

**Comment by HeshamHassan** [comment] 2018-04-01 08:27
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment] 2018-06-28 06:27
Any update??

**Comment by ahmedelbougha** [comment] 2018-06-28 10:26
@HeshamHassan 
This is a duplicate of a closed issue #321, please check my comments in the other ticket.

**Closed as completed** 2018-06-28 10:36 UTC
