### ISSUE TITLE
Custom Report Join Table fields

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#335] opened 2018-06-28 09:32 UTC
**URL:** http://skilledmatrix.com/admin/backend/reports/12/edit
**Path:** Admin> Backend> Custom Report
**Description:**
- [ ] We used a join table to join other tables together. But I don’t want to show its data in the report when it runs. The report creator enforces me to show at least one of its columns in the report.
We can check it together in report 12: Named “ Ali “
![image](https://user-images.githubusercontent.com/11155105/42026163-19ee814c-7acf-11e8-8b86-ce8e4b3dd74e.png)

**Comment by ahmedelbougha** [comment] 2018-06-28 10:00
@mahmoud-hussien1 
Please make sure to make the report contains at least one field, but don't make it mandatory to select columns from all tables.

**Comment by HeshamHassan** [comment] 2018-07-11 11:18
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment] 2018-07-18 11:53
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/47/issue-335-create-custom-validation-rule/diff

**Comment by ahmedelbougha** [comment] 2018-07-18 18:34
done, @HeshamHassan check and confirm.

**Comment by HeshamHassan** [comment] 2018-07-19 09:06
**@ahmedelbougha** 
I cannot check. the table order in the report changes each time I change the checking factors.

**Comment by HeshamHassan** [comment] 2018-07-22 10:52
@ahmedelbougha
Any update?

**Comment by ahmedelbougha** [comment] 2018-07-22 17:36
@HeshamHassan please create new custom report and check the functionality is working fine (create/edit/run) and if not please let me know.

**Comment by ahmedelbougha** [comment] 2018-07-31 16:50
@HeshamHassan any update??!!!

**Comment by ahmedelbougha** [comment] 2018-07-31 16:53
@HeshamHassan we added new field group to use it for ordering the table, check and confirm please.
@HeshamHassan, @Ali-Galal 
This issue is duplicate of issue #337 please close and concentrate on one issue only.

**Comment by HeshamHassan** [comment] 2018-07-31 17:11
**@ahmedelbougha** 
Kindly note:
Issue #337 is about the used tables order in the report.
Issue #335 is about the joining between tables and the mandatory fields.
Each issue of them affects the report and prevents the running of the report.

**Comment by ahmedelbougha** [comment] 2018-08-01 06:47
@HeshamHassan 
When is the last time did you try to create report? the functionality is working since some time and I didn't hear back from you about this.
FYI, I'll remove all old reports to avoid confusion and please start to make new ones.

**Comment by HeshamHassan** [comment] 2018-08-01 06:49
**@ahmedelbougha** 
Good
Remove all the old confusion report. So, I can create new clear reports.
Inform me when done to start my checking.

**Comment by ahmedelbougha** [comment] 2018-08-01 07:16
@HeshamHassan old reports have been removed.
Please note this issue has been opened according to this description:
```
We used a join table to join other tables together. But I don’t want to show its data in the report when it runs. The report creator enforces me to show at least one of its columns in the report.
We can check it together in report 12: Named “ Ali “
```
And this issue has been fixed since long time ago, so either close this issue and open another issue or stick to one issue to discuss all issues of Custom Reports.

Please confirm.

**Comment by HeshamHassan** [comment] 2018-08-01 09:36
**@ahmedelbougha** 
I cannot deal as well with the custom report module.
Kindly arrange an online appointment to fix all issues about that module.

**Comment by ahmedelbougha** [comment] 2018-08-01 10:15
@HeshamHassan 
You mean you cannot use the module.
If you cannot deal with the module, the close all related issues and create a new one of how to use.
@Ali-Galal 
Would you please check and confirm what is needed?

**Comment by Ali-Galal** [comment] 2018-08-02 07:00
@ahmedelbougha this issue has been settled 
@HeshamHassan  close this issue 
@HeshamHassan close issue #337 
@HeshamHassan open new issue contains all issues related to the custom report in checkbox items

**Closed as completed** 2018-08-06 11:09 UTC
