### ISSUE TITLE
Missing Downloads

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#307] opened 2018-03-28 10:44 UTC
**URL:** http://testing-engine.camelcasetech.com/admin/downloads
**Description:** There is no "Downloads Desktop App". The page is empty.

**Comment by HeshamHassan** [comment] 2018-04-01 08:27
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment] 2018-06-28 06:40
Any update??

**Comment by ahmedelbougha** [comment] 2018-06-28 10:33
@HeshamHassan 
This is not a bug, this should contains the desktop app there when it's compiled on the server.

**Comment by HeshamHassan** [comment] 2018-07-11 13:37
@ahmedelbougha 
Kindly determined the expected time to take the desk top app. alive?

**Comment by HeshamHassan** [comment] 2018-09-09 09:49
**@ahmedelbougha** 
Any update??

**Comment by HeshamHassan** [comment] 2018-09-26 11:36
**@ahmedelbougha**
Any update??

> @ahmedelbougha
> Kindly determined the expected time to take the desktop app. alive?

**Comment by ahmedelbougha** [comment] 2018-11-12 11:28
done, @HeshamHassan please confirm and close

**Comment by HeshamHassan** [comment] 2018-11-12 13:26
App. is available, but not installable. #367

**Comment by ahmedelbougha** [comment] 2018-11-21 14:47
@HeshamHassan 
Close this issue, and you have another issue for making the installer.

**Closed as completed** 2018-11-21 15:45 UTC
Labels: Fixed
